bcgov/bcparks-ar-api

- __tests__/global/data.json
- __tests__/park.test.js
- __tests__/subarea.test.js
- lambda/park/GET/index.js
- lambda/subarea/GET/index.js
- lambda/subarea/POST/index.js
- miscellaneous/Example Subareas/Backcountry Cabins.json
- miscellaneous/Example Subareas/Backcountry Camping.json
- miscellaneous/Example Subareas/Boating.json
- miscellaneous/Example Subareas/Day Use.json
- miscellaneous/Example Subareas/Frontcountry Cabins.json
- miscellaneous/Example Subareas/Frontcountry Camping.json
- miscellaneous/Example Subareas/Group Camping.json
- tools/convertParksSheet.js
###Jira Ticket
BRS-615
https://bcparksdigital.atlassian.net/jira/software/projects/BRS/issues/BRS-615
This ticket adds a unique ID number to each subarea. The numbers are sequential; the next sequential number can be used to identify new subareas as they need to be created. This UID is a better unique identifier to use both in partition/sort keys and in API calls, so the DynamoDB seeding script and lambdas have been updated accordingly. The updated data models are as follows:
```
Park:
pk: park
sk: <orcs>
example: park, 0001 = 'Strathcona Park'
SubArea:
pk: park::<orcs>
sk: <subAreaId>
example: subarea::0001, 0403 = 'Buttle Lake'
Config:
pk: config::<subAreaId>
sk: <activity>
example: config::0403, Day Use = 'Buttle Lake - Day Use (config)'
Record:
pk: <subAreaId>::<activity>
sk: <date> …
```
> BRS-615 adding subArea UID

- lambda/export/constants.js
- lambda/export/invokable/index.js
- lambda/formulaUtils.js
BRS-654/BRS-655
https://bcparksdigital.atlassian.net/browse/BRS-654
https://bcparksdigital.atlassian.net/browse/BRS-655
This change adds to and updates some formulae captured in the exporter. The new formulae are:
For Frontcountry Cabins:
`Total Attendance = Parties x 3.2`
For Day Use:
`Total Attendance = (Vehicles x 3.5) + (Buses x 40) + Trail counter`
Due to the exporter's reliance on S3 buckets to store reports, this change is difficult to test locally. The current AWS sandbox environment has these changes under the live API https://rtfwcnlgkf.execute-api.ca-central-1.amazonaws.com/api.
> BRS-654/655 updating formulae in the backend

- lambda/export/constants.js
- lambda/export/invokable/index.js
- lambda/formulaUtils.js
Reverts bcgov/bcparks-ar-api#55. 
Rolling this back as calling the `export-get` lambda causes it to repeat calling itself until throttled.
> Revert "BRS-654/655 updating formulae in the backend"

- lambda/export/constants.js
- lambda/export/invokable/index.js
- lambda/formulaUtils.js
BRS-654/BRS-655
https://bcparksdigital.atlassian.net/browse/BRS-654
https://bcparksdigital.atlassian.net/browse/BRS-655
NOTE: This change was originally implemented and then reverted due to the exporter lambdas looping indefinitely when encountering an error. 
This change adds to and updates some formulae captured in the exporter. The new formulae are:
For Frontcountry Cabins:
Total Attendance = Parties x 3.2
For Day Use:
Total Attendance = (Vehicles x 3.5) + (Buses x 40) + Trail counter
Due to the exporter's reliance on S3 buckets to store reports, this change is difficult to test locally. The current AWS sandbox environment has these changes under the live API https://n10uxmdaq0.execute-api.ca-central-1.amazonaws.com/api.
> BRS-654/655 adding formulae to backend

- __tests__/global/setup.js
- __tests__/global/teardown.js
- __tests__/park.test.js
- __tests__/subarea.test.js
- lambda/captchaUtil.js
- lambda/dynamoUtil.js
- lambda/export/GET/index.js
- lambda/export/invokable/index.js
- lambda/logger.js
- lambda/park/GET/index.js
- lambda/park/POST/index.js
- lambda/permissionUtil.js
- lambda/readConfig/index.js
- lambda/subarea/GET/index.js
- lambda/subarea/POST/index.js
- migrations/20220621153946-parkAndSubAreaRoles.js
- package.json
- tools/KeyCloakUtilities.js
- yarn.lock
This changes how roles are worked in A&R.  Filtering based on Park and/or Subarea for all api calls. Removed `POST park` as it's unused at the moment, but may come back soon.  If not, a new ticket should be put into the backlog to address the complete removal.
NB: This requires a migration to be run (20220621153946-parkAndSubAreaRoles) as well as this PR to be pulled down during testing of this back-end change:  https://github.com/bcgov/bcparks-ar-admin/pull/144
> BRS-643: Role assignment for Sub-areas in A&R

- lambda/formulaUtils.js
BRS-692:
Turned out to be fairly straightforward in this case, as the formula that is changing is not referenced outside of `formulaUtils`.
> BRS-692: updating basic revenue formula for exporter

- lambda/export/invokable/index.js
These columns are switched in our exporter. This change fixes the issue.
> NOBUG: fixing frontcountry camping party revenue and second car attendance formulas

- lambda/dynamoUtil.js
- migrations-data/addFromCSV.js
- migrations/20220825185430-newEntries-1.js
The `addToCSV` script that was used to migrate the new data in this ticket was built from a script that expects an empty DB to start with. As such there were errors occurring in some areas where a check for existing data needed to be performed. This change updates the `addToCSV` script to check for existing data in these cases. 
DEV and TEST DBs, where this migration was originally run before, will have this migration rerun. In the known cases where rerunning the migration will not solve the errors created by the previous migration run, the data will be manually updated in DEV and TEST (removing duplicates).
> BRS-701 fixes to migration script

- lambda/formulaUtils.js
Lambda doesn't like the logical nullish assigment operator `??=`
> BRS-652-2 changing logical nullish assignment

- migrations/20220922154247-addBundle.js
Ensuring park bundles show up correctly in our DB. When this is finished we should be able to stop relying on the Park Names Comparison Spreadsheet as the source of truth.
> BRS-799 migration to add park bundle

- lambda/dynamoUtil.js
Adding helper functions `getParks()` and `getSubAreas()` as these calls are used frequently. We do something similar in our DUP product already. 
A couple of the migrations run lately are dependent on these functions - but have been running smoothly since they were already in my repo, just uncommitted.
> BRS-799-2 dynamoUtil improvements

- __tests__/fiscalYearEnd.test.js
- __tests__/global/data.json
- __tests__/subarea.test.js
- lambda/dynamoUtil.js
- lambda/fiscalYearEnd/GET/index.js
- lambda/fiscalYearEnd/POST/index.js
- lambda/subarea/POST/index.js
- postman/BCParks Attendance and Revenue.postman_collection.json
- serverless.yml
- terraform/src/fiscalYearEnd.tf
- terraform/src/main.tf
- terraform/src/modules/cors-enabled-api-resource/main.tf
- terraform/src/modules/cors-enabled-api-resource/outputs.tf
- terraform/src/modules/cors-enabled-api-resource/variables.tf
- terraform/src/subarea.tf
This change includes the backend updates to enable locking/unlocking records.
There are 2 levels of locking: 1 on the record level against the record itself, and one at the fiscal year level, where all records within the fiscal year are locked against editing. If a record meets either one of these locking levels, it cannot be edited. 
New object `fiscalYearEnd` has been introduced with the following structure: 
```
pk: fiscalYearEnd
sk: 2023
isLocked: false
```
`sk` is the calendar year in which the fiscal year ends (2023 = 2022-04 to 2023-03). If `isLocked` is set to true, the fiscal year is locked against editing. 
New endpoints:
`GET ../fiscalYearEnd?fiscalYearEnd=2023` - get fiscalYearEnd object (to check locked status)
`POST ../fiscalYearEnd/lock?fiscalYearEnd=2023` - lock …
> BRS-502 Lock/Unlock records & fiscal years

- lambda/subarea/POST/index.js
Small error with the new `subarea/lock` endpoint fixed.
If we call `subarea/lock` on a record that doesn't yet exist, a blank record is initialized to track the lock/unlock status. This blank record was being initialized as 'unlocked' when it should be 'locked' upon initialization ONLY if it is created through the `/lock` endpoint.
> NOBUG - init record as locked if creating from /lock endpoint

- lambda/dynamoUtil.js
- lambda/export/invokable/index.js
`fiscalYearEnd` objects and `record` objects share the same `sk` format (YYYYMM).
This format is what the exporter uses to pull every record in the system currently, so the `fiscalYearEnd` objects are getting mixed in with the exported records and throwing syntax errors.
Added a `getRecords(subAreaObj, filter)` function to `dynamoUtils` to pull all records associated with a provided subarea. This is now the method used to collect all records in the system for the exporter.
> BRS-502-3: Exporter refactor - avoid pulling fiscalYearEnd objs.

- .github/workflows/PR-Tests.yml
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
> NOBUG - updating Actions to use Node16

- lambda/dynamoUtil.js
- lambda/fiscalYearEnd/POST/index.js
- lambda/subarea/POST/index.js
According to https://bcparksdigital.atlassian.net/browse/BRS-817, we need to prevent users from locking records & fiscal years if the month/fiscal year the record is in has not yet concluded.
This change includes the API changes to support this.
> BRS-817-2 preventing locking of future dates

- lambda/export/GET/index.js
https://bcparksdigital.atlassian.net/browse/BRS-849
The attribute `jobObj.progressState` was introduced on this ticket. Since this attribute does not exist on old job objects, a conditional expression was failing. 
This code ensures the new code is backwards compatible with old exporter job objects.
> BRS-849-2 ensuring jobObj backwards compatibility

- package.json
luxon code was introduced with lock/unlock but was not included as a dependency.
> BRS-867: adding luxon package

- migrations/20220922154247-addBundle.js
the dynamoutil function `getOne` return object format was updated to be similar to the other getters in dynamoutil in #77, but one migration which relied on the old format was not updated.
> NOBUG - getOne changed in migration script

- __tests__/global/data.json
- __tests__/park.test.js
- lambda/park/GET/index.js
BRS-971
https://bcparksdigital.atlassian.net/browse/BRS-971
This change ensures that legacy data is not returned by the API (for now). We do not have the front end set up in a way that can handle legacy parks/subareas/records yet. 
Updated UT mock data items to include legacy instances to ensure all tests still pass.
> BRS-971-3: ensuring front-end filters out legacy data (for now).

- terraform/src/export.tf
BRS-1115
https://bcparksdigital.atlassian.net/browse/BRS-1115
Improving timeout for `export-invokable` following a 120s timeout being too short.
Note: improving memory did not improve lambda time.
- 2048 MB = 110s run time
- 8192 MB = 107s run time
A more permanent solution will be handled in a future ticket (BRS-1118).
> BRS-1115: upping exporter timeout (temp)

- migrations-data/legacy-data/legacy-data-constants.js
NOBUG
https://bcparksdigital.atlassian.net/browse/BRS-971
In the schema that controls field mapping in the historical data migrations, under Frontcountry Camping, the field for 'Gross Shower Revenue' erroneously points to `otherRevenueGrossSani` values.
**What does this mean?**
In `dev` and `test` which have already had the migrations performed on them, historical values for  `otherRevenueGrossSani` may have been replaced with values for `otherRevenueShower`, and fields relying on `otherRevenueShower` values will be blank.
Prod is unaffected as the migration has not been run yet.
**Does that mean `dev` and `test` are completely borked?**
No, aside from the errors in historical data above. New system records and newly created records are unaffected, and it wouldn't be a good use of …
> NOBUG - mislabelled historical data item in schema

- __tests__/subArea.test.js
- lambda/permissionUtil.js
- lambda/subArea/DELETE/index.js
BRS-897
This  implements hard delete option for subareas.
If the archive flag is set to true, the function calls a function called "archiveSubArea" to archive the subArea instead of deleting it. If the archive flag is set to false or not included in the query string parameters, the function calls a function called "deleteSubArea" to delete the subArea.
The "deleteSubArea" function first removes the subArea from the "park" object by calling a function called "deleteSubAreaFromPark". It then deletes all records associated with the subArea by calling the "deleteSubAreaRecords" function and the "deleteActivityRecords" function.
The "deleteActivityRecords" function first deletes all activity configuration records associated with the subArea. …
> BRS-897: Implement hard delete.

- __tests__/subArea.test.js
- lambda/subArea/DELETE/index.js
BRS-897
This implements a soft-delete (setting `archived:true`) on the subarea record, as well as removing it from the park `subAreas` property.  This ensures that subareas are removed from standard flow in the UI, however the data is retained in the system.  UI updates will need to be done in order to adjust workflows to be able to show such records.
> BRS-897: Soft delete (archived=true) implementation for a subarea.

- __tests__/activity.test.js
- __tests__/variance.test.js
- lambda/activity/POST/index.js
- lambda/variance/GET/index.js
- lambda/variance/PUT/index.js
BRS-1214
https://bcparksdigital.atlassian.net/browse/BRS-1214
Updating the API to handle the new variance data model: 
```
pk: variance::<ORCS>::<activityDate>  // activityDate = YYYYMM
sk: <subAreaId::activity
```
Done this way to accommodate the desired search characteristics in the front end. 
Bundles are temporal and do not necessarily remain consistent RE: which parks and subareas they affect so this filter was dropped from consideration. Now a user must know at minimum the `park` and `date` they are searching for. This shards the database in a way that gives high cardinality and fast responses as the database scales in size. 
Roles are now enforced on Variance GET/PUT. 
Filtering by variance `resolved` status is now supported. 
The old data model hasnt landed in PROD yet so no …
> BRS-1214 pt1: Updating API to handle new variance data model

- __tests__/activity.test.js
- lambda/activity/POST/index.js
BRS-1198
https://bcparksdigital.atlassian.net/browse/BRS-1198
Changing the `fields` property of variance objects from
``
fields: [field1, field2, field3] ...
``
to 
```
fields: [{ key: field1, percentageChange: 0.23}, { key: field2, percentageChange: 0.24}, { key: field3, percentageChange: 0.25}] ...
```
Doing this as it has been requested that the exported variance report include the percentage change for each field that triggered a variance. Want to get this change in before the variance-creating API changes hit PROD so no migration is needed.
> BRS-1198 pt 1: adding percentageChange to variance object

- __tests__/export-variance.test.js
- __tests__/global/data.json
- lambda/constants.js
- lambda/export-variance/GET/index.js
- lambda/export-variance/invokable/index.js
- serverless.yml
- terraform/src/main.tf
- terraform/src/roles.tf
- terraform/src/variance-export.tf
BRS-
https://bcparksdigital.atlassian.net/browse/BRS-1198
Part 1 - this change largely copies/reduces the code used for the main exporter. 
New endpoint:
```
.../api/export-variance
```
You must pass in a `fiscalYearEnd` query param so that the search can parse only 1 year at a time
```
.../api/export-variance?fiscalYearEnd=2024 // will get you results from 202304-202403
```
It's predicted that some of these queries could take a long time to complete, so when the endpoint is called, a job id is set up and the heavy lifting is completed by an asynchronous Lambda invokable. The job id is a md5 hash generated from the users roles and the queryParams passed in (only `fiscalYearEnd` for now). This way, like the exporter, users with the same roles & requests can download existing reports …
> BRS-1198: pt1 variance record creation and export 

- __tests__/global/data.json
- lambda/export-variance/GET/index.js
BRS-1198
https://bcparksdigital.atlassian.net/browse/BRS-1198
Minor fix to previous BRS-1198 commit - when creating the job id hash from the users roles & params, the `getJob` param was included, preventing ease of lookup by hash. The `getJob` param is now deleted before the job hash is created/searched.
This change must be merged before the front-end changes will work
> BRS-1198-2 ignore getJob boolean from job id creation

- lambda/activity/POST/index.js
BRS-1244
https://bcparksdigital.atlassian.net/browse/BRS-1244
The calculator that determined the correct last 3 years worth of records to be considered in the historical average calculation was including the current year in the calculation if it existed. The real calculation should not factor in existing current year values when calculating the 3 year average. 
Old behaviour:
```
currentYear: 2023
historicalYears: [2023, 2022, undefined] // doesnt go past 2022
```
New behaviour:
```
currentYear: 2023
historicalYears: [2022, undefined, undefined]
```
> BRS-1244 fixing previous year average calculator

- lambda/activity/POST/index.js
- lambda/varianceUtils.js
BRS-1216
https://bcparksdigital.atlassian.net/browse/BRS-1216
Variance trigger is now inclusive of the +/- 20% threshold.
Before:
```
Variance triggered when: |variance percent| > 20%
```
Now:
```
Variance triggered when: |variance percent| >= 20%
```
Also fixed: Variance records are now deleted when all fields are brought within the threshold AND no notes exist on the activity record.
> BRS-1216: variance trigger threshold now inclusive

- README.md
- __tests__/global/data.json
- __tests__/global/settings.js
- __tests__/global/setup.js
- __tests__/global/teardown.js
- __tests__/name-update.test.js
- lambda/dynamoUtil.js
- lambda/nameUpdate/index.js
- serverless.yml
- terraform/src/db.tf
- terraform/src/nameUpdate.tf
- terraform/src/variables.tf
Fixes #233 
Two new environment variables have been setup - their default configurations are setup in the parameter store.
There is a cronjob that is setup to run every midnight.  The first run of the job will update ALL names in the A&R table to whatever they are set to in the data register.  On subsequent runs, the code will only update the records in question that have changed from the data register.
A new index against the A&R table is setup (orcs-index) which allows the code to efficiently query all records via orcs.
TODO: Update the parameter store variables with TEST and PROD data that point to the appropriate API endpoint for DR TEST and PROD.
> 233: Hookup A&R to Data Register.

- __tests__/name-update.test.js
- lambda/nameUpdate/index.js
This updates the lookup logic so that it finds for things like `0228` vs `228` as `A&R` does not trim the prefix (yet)
> 203 Update prefixing of orc numbers when doing local lookups.

- serverless.yml
PDR-224
Serverless.com issue for cloudwatch alarm on `nameUpdate` - looks like this was missed on the last serverless.com updates.
> CW Alarm for nameUpdate serverless.com issue

- migrations/20240125103944-fixSubAreaRoles.js
AR-293
https://github.com/bcgov/bcparks-ar-admin/issues/293
Adding migration to fix subarea roles.
There are instances in prod where subarea roles are incorrect:
- park::8306 has 1020 in its role
- park::0347 has 0347::612 in its role
The correct way to format a role is as follows:
```{orcs}:{sk}```
ie:
```8306:1020``` and ```0347:0612```
Note that leading zeros are included.
> AR-293: Adding migration to fix subarea roles

- lambda/park/POST/index.js
- migrations/20240126140700-fixParkRoles.js
API was creating new parks with roles as String Sets when the existing parks use Lists. This was causing some parks to not appear in the front end with non-sysadmin perms.
> Park roles are now List and not String Set

- __tests__/activity.test.js
- __tests__/variance.test.js
- lambda/activity/POST/index.js
- lambda/varianceUtils.js
Relates to PDR-255.
Updates the `activityPOST` endpoint to return a variance warning when variances are triggered instead of saving the activity record.
If `warn=true` is provided in the POST query param, the API will check to see if variances are triggered. If a variance is triggered AND no notes are provided, the activity POST is interrupted and the would-be variance object is returned, but not saved to the database. The activity record is not updated.
Inversely, if `warn=true` and notes are provided, the API will update the activity activity record. If a variance is triggered, a variance object will be created in the database but the user will not be warned.
> PDR-255 warn if variance triggered

- migrations-data/updateSubareaName.js
- migrations/20240308143600-subAreaNameUpdates.js
Addresses https://github.com/bcgov/bcparks-ar-api/issues/313 and https://github.com/bcgov/bcparks-ar-api/issues/311.
Performs the migrations necessary to complete the above tickets and adds a script to `/migrations-data` to assist with renaming existing subarea names in the future.
> PDR-313: adding migration and subarea name update script

- lambda/dynamoUtil.js
- migrations/20240313090100-modernizeVarianceObjs.js
- tools/progress-indicator.js
https://github.com/bcgov/bcparks-ar-admin/issues/322
Migration script will add the fields `historicalAverage` and `yearlyAverages` to the `fields` property of variance reports.
When variance reports were introduced, they were only implemented for records that were created during or after 2022, since the data from prior years was unverifiable. Therefore, this migration is only applied to >=2022 records, to remove the risk of creating inaccurate data in any variance records prior to 2022.
> PDR-322 migration to update variance records

- package.json
- serverless.yml
- webpack.config.js
- yarn.lock
Hitting 'EMFILE - too many open files' error when deploying to DEV. Attempting to rectify this by using the serverless recommended approach of including webpack and packaging individually.
> NOBUG - adding webpack to package individually

- .github/workflows/deploy_prod.yaml
- .github/workflows/deploy_test.yaml
- README.md
- arSam/handlers/activity/GET/index.js
- arSam/handlers/export-variance/GET/index.js
- arSam/handlers/export-variance/GET/package.json
- arSam/handlers/export/GET/index.js
- arSam/handlers/fiscalYearEnd/GET/index.js
- arSam/handlers/park/GET/index.js
- arSam/handlers/readConfig/index.js
- arSam/handlers/variance/GET/index.js
- arSam/layers/baseLayer/Makefile
- arSam/layers/baseLayer/baseLayer.js
- arSam/layers/constantsLayer/Makefile
- arSam/layers/formulaLayer/Makefile
- arSam/layers/functionsLayer/Makefile
- arSam/layers/functionsLayer/functionsLayer.js
- arSam/layers/functionsLayer/nodejs/package.json
- arSam/layers/keycloakLayer/Makefile
- arSam/layers/permissionLayer/Makefile
- arSam/layers/varianceLayer/Makefile
- arSam/package.json
- arSam/yarn.lock
- Fix to CORS error from `sendResponse`, this was cropping up in the dev environment
- Update other deploys to no longer reference `stack-name`
- Fixes to `Makefiles` to also `yarn cache clear` etc. (until we're sure the dependency errors are gone)
- Update `crypto` dependency as it has been deprecated (was flashing error/warning in `sam build`)
> BRS-291-13: Update deploys, makefiles; change crypto, fix cors errors

- arSam/layers/baseLayer/baseLayer.js
- arSam/template.yaml
Remove authorizer for `/config`, fix broken test
> BRS-291-16: Remove authorizer for /config, fix broken test

- arSam/template.yaml
[BRS-326](https://github.com/orgs/bcgov/projects/49/views/1?filterQuery=326&pane=issue&itemId=59089136)
[BRS-291](https://github.com/orgs/bcgov/projects/49/views/1?filterQuery=291&pane=issue&itemId=47054932)
- Add logging param to swap between `debug` and `info`
- Add nameUpdate cron schedule
- [Fixes from QA comment in 291](https://github.com/bcgov/bcparks-ar-api/issues/291#issuecomment-2259632337)
> BRS-326-2: QA fixes for nameUpdate cron, add logging param

- arSam/template.yaml
[BRS-326](https://github.com/orgs/bcgov/projects/49/views/1?filterQuery=326&pane=issue&itemId=59089136)
[BRS-291](https://github.com/orgs/bcgov/projects/49/views/1?filterQuery=291&pane=issue&itemId=47054932)
- [Fixes from QA comment in 291](https://github.com/bcgov/bcparks-ar-api/issues/291#issuecomment-2271459984).
- Fix DATA_REGISTER_NAME_ENDPOINT typo in `template.yaml`
> BRS-326-5: Fix typo for DR endpoint

- arSam/handlers/export-variance/__tests__/export-variance.tests.js
- arSam/handlers/export-variance/invokable/index.js
- arSam/handlers/export/__tests__/export.test.js
- arSam/layers/constantsLayer/constantsLayer.js
- arSam/template.yaml
[#357](https://github.com/bcgov/bcparks-ar-admin/issues/357)
- Update the Variance Report Export to contain columns for each variance report item
- Take the items in EXPORT_VARIANCE_CONFIG and flatten the keys into an array
- Use the flattened array to compare against the `record.fields`, which are the variance items found in each record
- If the key matches a field, then we push the key to the record under their own item `record[field.key]` (as opposed to daisy chaining all the variances under `fields`).
- Also, increase timeout for the exporter to fix issue from [#291 ](https://github.com/bcgov/bcparks-ar-api/issues/291) as they seem to take a little longer with the V3 SDK in prod
- Linting fixes to test files and `template.yaml`
> BRS-357: Separate each variance into individual cells, increase export timeouts

- arSam/handlers/export-variance/invokable/index.js
- arSam/layers/constantsLayer/constantsLayer.js
- arSam/template.yaml
[#357](https://github.com/bcgov/bcparks-ar-admin/issues/357)
- Add missing Group Camping constants and account for their columns in CSV generation
- Increase memory in invokables so we don't have to wait for hours (and fix timeout issues)
> BRS-257-2: Fix missing group camping, increase memory for invokables

- arSam/handlers/export-missing/invokable/index.js
- arSam/layers/baseLayer/baseLayer.js
BRS-254
[#254](https://github.com/bcgov/bcparks-ar-admin/issues/254)
- Fixed an issue with the download after "Generate report" is clicked. Now looks for the string 'null' as it is passed from the event. Also fixed a typo where `skMax` wasn't having its hyphen replaced before constructing the query, leading to an error.
- Fixed an issue with the notes in the Null/Missing Export as mentioned [here](https://github.com/bcgov/bcparks-ar-api/issues/377#issuecomment-2505184502)
> BRS-254-Fix: skMax Typo, null Check, and a Fix to the Notes in Missing Export

- arSam/handlers/export-missing/invokable/index.js
- arSam/migrations/202410181342-fixDataDiscrepancies.js
BRS-377
#377
- Fixed an issue where we weren't checking if an item had a "0" input, which should have been flagged as "Missing Data" ([#412](https://github.com/bcgov/bcparks-ar-admin/issues/414))
- Fixed a bug where empty notes were showing as `undefined` ([#413](https://github.com/bcgov/bcparks-ar-admin/issues/412))
- Fix to data discrepancy migration - part of the function was wrongly nested, which led to a duplication of TransactionWrite operations for the same record, which led to batch errors 
- Ticket: #380
- Also added logic to skip `isLegacy` / `(historical)` data
- Also changed it so the Notes output is just a single column, which should improve readability
- Even more comments, because comments are important!
> BRS-377-1: Fix Missing Export for "0" Data and Legacy Data; Fix Migration

- arSam/handlers/export/invokable/index.js
- arSam/handlers/export/invokable/package.json
- arSam/migrations/migrate-historical/2000-2016/migrate.js
- arSam/migrations/migrate-historical/legacy-data-constants.js
- arSam/migrations/migrate-historical/legacy-data-functions.js
- arSam/migrations/migrate-historical/purgeLegacy.js
BRS-237
#237 
- Copy over and update `/migrations-data/legacy-data/2017-2019` into new `migrations` folder for SAM
- Small tweaks to remove Keycloak params and subsequent role creation functionality
- Update to use AWS SDK v3
- Small logic tweaks to avoid importing empty cells in `.xlsx` file
> BRS-237 - Migration for Historical Data 2000-2016

- .gitignore
- arSam/handlers/export/invokable/index.js
- arSam/layers/constantsLayer/__tests__/constantsLayer.test.js
- arSam/layers/constantsLayer/constantsLayer.js
- arSam/layers/formulaLayer/formulaLayer.js
- docs/README.md
- docs/data_model.json
BRS-389
[#389](https://github.com/bcgov/bcparks-ar-admin/issues/389)
- `Winter standard` and `Winter SSCFE` now accepted data points in A&R
- Add Winter Camping data fields to attendance calculation and export fields
> BRS-389 - Implement Winter Camping Data Fields

- arSam/migrations/20250306155100-addRegionData.js
Relates to #427.
A quick script to add four new datatypes to the database. Refer to the ticket for rationale for this action.
The data for this migration is provided in #427 as an `xlsx` file.
This ticket will not deal with subareas with existing Region/Section/ManagementArea/Bundle entries. These items can be added to the database without interfering with existing items. 
Another ticket can be made to sync existing subarea values with the values that will be added by this migration.
The four new types are: Region, section, management area, and bundle. The hierarchy is as follows:
```
.
├── Region/
│   ├── Section/
│   │   ├── ManagementArea
│   │   ├── ManagementArea
│   │   └── ManagementArea
│   ├── Section
│   └── Section
├── Region
└── Region
.
├── Bundle
├── Bundle
└── Bundle
``` …
> AR-472-1 migration script to add region/section/managementArea/bundle to database

- arSam/__tests__/mock_data.json
- arSam/handlers/bundle/GET/index.js
- arSam/handlers/region/GET/index.js
- arSam/handlers/region/__tests__/region.test.js
- arSam/package.json
- arSam/template.yaml
Relates to [#427](https://github.com/bcgov/bcparks-ar-admin/issues/427)
Adding regions GET endpoint.
```
GET .../api/regions
```
Returns all regions in the database.
```
GET .../api/regions?regionId=<regionId>
```
Add `regionId` as queryStringParameter to get specific region.
> AR-427-2 Adding regions GET endpoint

- arSam/template.yaml
Mislabeled path in template file is breaking the build.
> NOBUG: fixing bundle path

- arSam/handlers/subArea/GET/index.js
- arSam/template.yaml
Relates to https://github.com/bcgov/bcparks-ar-admin/issues/427
Subarea GET was never implemented (returns 501). Because of this, OPTIONS preflight on subarea PUT was borking.
Added OPTIONS clause to GET endpoint. Seems to have fixed the issue.
> AR-427-4 Adding OPTIONS handling method to Subarea GET
