bcgov/bcparks-ar-api

.github/workflows/deploy_dev.yml
.github/workflows/deploy_prod.yml
.github/workflows/deploy_test.yml
.github/workflows/pull_request_template.md
terraform/dev/terragrunt.hcl
terraform/prod/terragrunt.hcl
terraform/test/terragrunt.hcl

BRS-507 Part 1: setting up GH actions deployment pipeline for API
https://bcparksdigital.atlassian.net/browse/BRS-507
Pipeline for admin coming in a separate future ticket.

BRS-507 part 1: setting up GH Actions deployment pipeline for API

---

.gitignore
lambda/dynamoUtil.js
lambda/readConfig/index.js
serverless.yml
terraform/src/settings.tf
tools/dynamoRestore.js

BRS-557
https://bcparksdigital.atlassian.net/browse/BRS-557
Adding readConfig Lambda function.

BRS-557 add readConfig Lambda

---

terraform/src/roles.tf
terraform/src/settings.tf

BRS-557 adding configuration role and policy to terraform

BRS-557 adding config role and policy

---

terraform/src/roles.tf

Reverts bcgov/bcparks-ar-api#21

Revert "BRS-501: Adding scan permissions to export lambda"

---

tools/KeyCloakUtilities.js

This is a script that loads keycloak roles by reading the xlsx sheet.  We need to prefix orcs as subarea names are conflicting.

BRS-299: Role loader script

---

lambda/dynamoUtil.js

NOBUG -  analogous change to https://github.com/bcgov/parks-reso-api/pull/133.

NOBUG - dynamoUtil.js improvements

---

lambda/export/constants.js
lambda/export/invokable/index.js
lambda/formulaUtils.js

https://bcparksdigital.atlassian.net/browse/BRS-652
Several new fields added to the A&R export sheet in accordance with ticket above.

BRS-652 updated CSV report

---

lambda/export/constants.js
lambda/export/invokable/index.js

BRS-823 Update A&R CSV export report column titles
https://bcparksdigital.atlassian.net/browse/BRS-823

BRS-823: Text updates to export

---

lambda/export/invokable/index.js

Jira Ticket:
BRS-823
Jira Ticket URL:
https://bcparksdigital.atlassian.net/browse/BRS-823

BRS-823: Corrected order for fiscal year display

---

lambda/park/GET/index.js
lambda/readConfig/index.js
lambda/subarea/GET/index.js
lambda/subarea/POST/index.js
terraform/src/export.tf
terraform/src/fiscalYearEnd.tf
terraform/src/park.tf
terraform/src/settings.tf
terraform/src/subarea.tf

This improves logging levels by default in the API, as well as enhancing some of the output.

BRS-947: Improve Logging levels in the DUP and A&R api

---

lambda/permissionUtil.js
postman/A&R - DEV.postman_environment.json
postman/A&R - LOCAL.postman_environment.json
postman/A&R - TEST.postman_environment.json
tools/KeyCloakUtilities.js

This points to the new loginproxy OIDC by default.

BRS-975: Point to new loginxproxy OIDC.

---

.github/workflows/deploy_dev.yml
.github/workflows/deploy_prod.yml
.github/workflows/deploy_test.yml

BRS-961
https://bcparksdigital.atlassian.net/browse/BRS-961
Changing artifact directory to just short_hash.

BRS-961: Changing artifact directory to just short_hash

---

__tests__/dynamoUtil.test.js
__tests__/export.test.js
__tests__/fiscalYearEnd.test.js
__tests__/global/data.json
__tests__/park.test.js
__tests__/subarea.test.js
lambda/permissionUtil.js
package.json

BRS-950
https://bcparksdigital.atlassian.net/browse/BRS-950
Updated tests for `park`, `subarea`, and `fiscalyear`.
Added some tests for `export`.
Consolidated all tests into one commit for cleaner history.

BRS-950: Updated unit tests

---

migrations-data/legacy-data/2017-2019/migrate.js
migrations-data/legacy-data/legacy-data-functions.js
migrations-data/legacy-data/purgeLegacy.js
tools/KeyCloakUtilities.js

BRS-971
https://bcparksdigital.atlassian.net/browse/BRS-971
Last change necessary for the migration - this change is to include the addition/deletion of KC roles when migrating/deleting legacy records. To run migrate now you must provide the target env and a valid token for the env to run: 
```
node migrate.js dev <token>
```
or 
```
node purgeLegacy.js dev <token>
```

BRS-971-4: update KC roles on add/delete legacy item

---

__tests__/export.test.js
__tests__/fiscalYearEnd.test.js
__tests__/global/data.json
__tests__/park.test.js
__tests__/subarea.test.js
lambda/export/GET/index.js
lambda/export/invokable/index.js
lambda/park/GET/index.js
lambda/permissionUtil.js
package.json

BRS-989
https://bcparksdigital.atlassian.net/browse/BRS-989
This enables the A&R export page to be usable by non-sysadmins.  Depending on the role assigned to you in Keycloak, the back-end will generate only the reports you are allowed to see.  Combine with https://github.com/bcgov/bcparks-ar-admin/pull/219

BRS-989: Enable export A&R report by roles.

---

__tests__/dynamoUtil.test.js
__tests__/global/settings.js
__tests__/global/setup.js
__tests__/global/teardown.js
lambda/dynamoUtil.js

BRS-897
The incrementAndGetNextSubAreaID() function is an asynchronous function that returns a Promise. When called, the function increments the value of the lastID attribute in a DynamoDB item with a primary key of 'subAreaID' by 1 and returns the new value as a string.
None.
The function returns a Promise that resolves to the new value of the lastID attribute as a string.
To update the item, the function uses the AWS SDK's dynamodb.updateItem() method, which takes an object with the following properties:
`TableName`: The name of the DynamoDB table to update.
`Key`: An object that specifies the primary key of the item to update. In this case, the key is the pk attribute with a value of `subAreaID`
`UpdateExpression`: A string that …

BRS-897: Stub for setting up the lastID set for a subAreaID.

---

terraform/src/db-config.tf

BRS-897
This adds the config definition for config table.

BRS-897: Adding config tf.

---

terraform/src/db-config.tf

BRS-897
This adjusts the backup name resource.

BRS-897: Tweak backup plan.

---

terraform/src/db-config.tf

BRS-
Adjust db to normal table instead of IA.

BRS-897: Adjust db

---

lambda/activity/PUT/index.js
serverless.yml

BRS-897
Stubbing out activity put.

BRS-897: Stubbing out activity put

---

lambda/dynamoUtil.js
lambda/export/invokable/index.js
terraform/src/export.tf

BRS-1131
https://bcparksdigital.atlassian.net/browse/BRS-1131
Updating exporter timeout to 15 minutes and filtering historical items from the query until historical records can be properly accounted for.

BRS-1131: filtering historical items from exporter

---

lambda/activity/GET/index.js
lambda/park/GET/index.js

BRS-972
https://bcparksdigital.atlassian.net/browse/BRS-972
Changes to allow legacy records to be surfaced in the front end as part of BRS-972

BRS-972 surface legacy records in the front end

---

yarn.lock

This updates a number of package lock dependencies.

NOBUG: Update package lock file.

---

tools/dynamoRestore.js

NOBUG
Juicing up `dynamoRestore.js` to leverage `batchWriteItem` to batch write when restoring tables instead of one-by-one `putItem`.
Huge gainz observed.

NOBUG: beefing up dynamoRestore

---

package.json
serverless.yml
yarn.lock

BRS-1139
This updates outdated packages from potentially breaking versions.

BRS-1139: Update outdated package dependencies.

---

serverless.yml

BRS-1139
Updating serverless.yml

BRS-1139: Updating packages.

---

serverless.yml

BRS-1139
Updating deployment packaging.

BRS-1139: Updating deployment packaging.

---

package.json
yarn.lock

BRS-1139
This adds missing packages.

BRS-1139: Adding missing packages.

---

serverless.yml

BRS-1139
This updates the package configuration for serverless.

BRS-1139: Updating package configuration.

---

__tests__/export.test.js

BRS-1139
This moves the export utility functions into the common area,

BRS-1139: Update tests.

---

serverless.yml
yarn.lock

NOBUG: Fixing package lock.

---

yarn.lock

Further updates to the lock file.

NOBUG: Further updates.

---

terraform/src/park.tf

NOBUG
Fixing park post integration.

NOBUG: Fixing park post integration

---

terraform/src/park.tf

NOBUG
https://bcparksdigital.atlassian.net/browse/BRS-
Park post fix.

NOBUG: Park post fix

---

terraform/src/park.tf

NOBUG
Fixed park post permission issue.

NOBUG: fixed park post permission issue

---

package.json
yarn.lock

NOBUG
Adding Axios to packages.

NOBUG: Adding Axios to packages

---

lambda/keycloakUtil.js

This removes warnings in console due to missing declarations.

NOBUG: Removes warnings in console due to missing declarations.

---

terraform/src/roles.tf

This updates the db access rules.

NOBUG: Update database configuration.

---

terraform/src/subArea.tf

NOBUG
Adding env var for config table name.

NOBUG: Adding env var for config table name

---

lambda/subArea/POST/index.js
terraform/src/subArea.tf

BRS-1048
https://bcparksdigital.atlassian.net/browse/BRS-1048
This updates the env vars so that the KC url/client will be correct.

BRS-1048: Updating env vars for callout to KC.

---

terraform/src/subArea.tf

BRS-1048
https://bcparksdigital.atlassian.net/browse/BRS-1048
This updates the client id for KC.

BRS-1048: Update client id

---

lambda/subArea/POST/index.js

This updates the separator for KC role creation.

NOBUG: Update keycloak role separation.

---

lambda/variance/GET/index.js
lambda/variance/POST/index.js
lambda/variance/PUT/index.js
serverless.yml
terraform/src/main.tf
terraform/src/variance.tf
terraform/tools/terragrunt.hcl

BRS-1192
https://bcparksdigital.atlassian.net/browse/BRS-1192
Stubbing out variance endpoints.

BRS-1192: Stubbing out variance endpoints

---

__tests__/variance.test.js
lambda/variance/GET/index.js
package.json
serverless.yml
yarn.lock

BRS-1192
https://bcparksdigital.atlassian.net/browse/BRS-1192
- The code imports several utility modules (dynamoUtil, responseUtil, permissionUtil, and logger) and extracts specific functions and constants from them.
- The exported handler function is an AWS Lambda function that takes in event and context parameters. It is an asynchronous function (async) that handles incoming requests.
- The logger.debug statement logs the incoming event object for debugging purposes.
- Inside a try block, the code attempts to decode the JSON Web Token (JWT) contained in the event object using the decodeJWT function. The decoded token is stored in the token variable.
- The resolvePermissions function is then called with the token to obtain a permissionObject that contains information about the user's …

BRS-1192: Added GET for /variance

---

.gitignore
__tests__/variance.test.js
lambda/varianceUtils.js

BRS-1193
https://bcparksdigital.atlassian.net/browse/BRS-1193
Added variance util.

BRS-1193: Added variance util

---

__tests__/variance.test.js
lambda/variance/PUT/index.js

BRS-1172
https://bcparksdigital.atlassian.net/browse/BRS-
This adds the PUT methods for variance endpoint.

BRS-1172: Adding PUT for variance

---

lambda/activity/POST/index.js

BRS-898
https://bcparksdigital.atlassian.net/browse/BRS-898
This updates logic for checking fields on variances.

BRS-898: Update logic for checking fields on variances.

---

__tests__/variance.test.js
lambda/activity/POST/index.js
lambda/variance/PUT/index.js

BRS-1191
https://bcparksdigital.atlassian.net/browse/BRS-1191
This updates the back-end to reflect notes field label name.

BRS-1191: Fix for notes field name.

---

lambda/activity/POST/index.js

BRS-1212
https://bcparksdigital.atlassian.net/browse/BRS-1212
This will ensure a variance record is created when the notes field is populated.

BRS-1212: Create a variance record if notes are present.

---

__tests__/variance.test.js
lambda/activity/POST/index.js
lambda/varianceUtils.js

BRS-1216
https://bcparksdigital.atlassian.net/browse/BRS-1216
Variance Message Calculation: The `varianceMessage` is now correctly calculated based on the comparison between `percentageChangeAbs` and `variancePercentage`. It will accurately indicate whether variance is triggered or not.
Handling Division by Zero: The code now handles the division by zero scenario when calculating the `percentageChange`. If `averageHistoricValue` is zero, the `percentageChange` is set to 0, preventing any division by zero error.
Math.round() for Rounding: The code now uses Math.round() for rounding the percentage change and the absolute percentage change, ensuring more precise rounding.

BRS-1216: Fix variance calculations.

---

.github/workflows/deploy_dev.yaml
terraform/terragrunt.hcl

BRS-1157
https://bcparksdigital.atlassian.net/browse/BRS-1157
This moves the terraform action from TFC to TF via S3.

BRS-1157: Replace Terraform Cloud with Terraform via S3.

---

.github/workflows/deploy_dev.yaml
terraform/terragrunt.hcl

Reverts bcgov/bcparks-ar-api#177

Revert "BRS-1157: Replace Terraform Cloud with Terraform via S3."

---

.github/workflows/deploy_dev.yaml
terraform/terragrunt.hcl

Reverts bcgov/bcparks-ar-api#178

Revert "Revert "BRS-1157: Replace Terraform Cloud with Terraform via S3.""

---

.github/workflows/deploy_dev.yaml

BRS-1152
Adding cli variables for TF runner.

BRS-1152: Adding cli variables.

---

.github/workflows/deploy_dev.yaml

Reverts bcgov/bcparks-ar-api#181

Revert "BRS-1152: Adding cli variables."

---

.github/workflows/deploy_dev.yaml

BRS-1152
Fix terragrunt not to apply to all envs.

BRS-1152: Fix terragrunt not to apply to all envs.

---

.github/workflows/deploy_dev.yaml

BRS-1152
Updating cli command for TF.

BRS-1152: Updating cli command for TF.

---

.github/workflows/deploy_dev.yaml

BRS-1152
Update global option.

BRS-1152: Update global option.

---

.github/workflows/deploy_dev.yaml

BRS-1152: Update cli arguments.

---

.github/workflows/deploy_dev.yaml

BRS-1152: Update cli.

---

terraform/terragrunt.hcl

BRS-1152
Update the env var lookup.

BRS-1152: Update env var lookup.

---

.github/workflows/deploy_dev.yaml
terraform/terragrunt.hcl

BRS-1152
Update bucket and cli command.

BRS-1152: Update bucket and cli command.

---

terraform/terragrunt.hcl

BRS-1152: Output s3 bucket.

---

.github/workflows/deploy_dev.yaml
terraform/terragrunt.hcl

BRS-1152: Update options.

---

.github/workflows/deploy_dev.yaml

BRS-1152: Fix cli.

---

.github/workflows/deploy_dev.yaml

BRS-1152: Update auto approve.

---

.github/workflows/deploy_dev.yaml

BRS-1152: Remove lock.

---

.github/workflows/deploy_dev.yaml

BRS-1152: Remove lock forced.

---

.github/workflows/deploy_dev.yaml

BRS-1152 
https://bcparksdigital.atlassian.net/browse/BRS-1152 
remove lock file.

BRS-1152 remove lock file.

---

.github/workflows/deploy_prod.yaml
.github/workflows/deploy_test.yaml

BRS-1152
Adding test/prod deployments for TF via S3.

BRS-1152: Adding test/prod deployments for TF via S3.

---

.github/workflows/deploy_dev.yaml
.github/workflows/deploy_prod.yaml
.github/workflows/deploy_test.yaml
README.md

BRS-1152
Adding repo variables and updating documentation.

BRS-1152: Adding repo variables and updating documentation.

---

.github/workflows/deploy_prod.yaml
.github/workflows/deploy_test.yaml

BRS-1152
Adding oidc perms on test/prod.

BRS-1152: Adding oidc perms on test/prod.

---

.prettierrc.json
lambda/activity/POST/index.js

BRS-1244
https://bcparksdigital.atlassian.net/browse/BRS-1244
Retain variance fields if variance note is provided.

BRS-1244: retain variance fields if variance note is provided

---

lambda/activity/POST/index.js

BRS-1244
https://bcparksdigital.atlassian.net/browse/BRS-1244
Fixing issues variance is not triggering if there are no previous records.

BRS-1244: Fixing issues variance is not triggering if there are no previous records

---

__tests__/subAreaUtils.test.js
lambda/subAreaUtils.js
migrations/20230803145347-rolesTypeFix.js

BRS-1247
https://bcparksdigital.atlassian.net/browse/BRS-1247
Fixing type issues for subarea roles.

BRS-1247: Fixing type issues for subarea roles

---

lambda/export-variance/GET/index.js

BRS-1198
https://bcparksdigital.atlassian.net/browse/BRS-1198
Fixing variance exporter issue. Associated FE fix to come.

BRS-1254 fixing variance export backend

---

lambda/export-variance/GET/index.js
lambda/export-variance/invokable/index.js

BRS-1254
https://bcparksdigital.atlassian.net/browse/BRS-1254
Main issue: env variable `S3_BUCKET_DATA` which contains the name of the S3 bucket where the exported record is stored was incorrectly named `S3_BUCKET`. 
Also: QOL change added which shows incremental creation of exported report instead of appearing to hang at 10%, even though it is working.

BRS-1254 fixing variance exporter 2

---

__tests__/export-variance.test.js
__tests__/global/data.json
lambda/export-variance/GET/index.js

BRS-1263
https://bcparksdigital.atlassian.net/browse/BRS-1263
Fiscal year end now required in `export-variance` api calls. Deploy with associated BRS-1263 change in `admin` for full change to take effect.

BRS-1263 fiscal year end change

---

migrations/20230815153845-seedVariance.js
tools/dynamoRestore.js
tools/progress-indicator.js

BRS-1261
https://bcparksdigital.atlassian.net/browse/BRS-1261
This is a migration to seed the A&R database with variances. It reuses code from existing endpoints that create variances, so the same conditions for variance creation are followed. 
This migration will only seed variances for the year it was run (2023), and for months that have already passed or are in progress (<=August). It will not overwrite existing variances.  
Bonus: reusable code for console progress updates has been added under `progress-updates.js`. `dynamoRestore.js` has been updated with the latest reusable code.

BRS-1261 seed variances

---

migrations/20230815153845-seedVariance.js

BRS-1261
https://bcparksdigital.atlassian.net/browse/BRS-1261
NOTE: this ticket is already complete. I had to make a few minor hotfixes to the script to improve logging during lengthy migrations. this ticket is just to keep our migration script history up to date.

BRS-1261: minor script updates

---

migrations/20230816150824-sectionUpdates.js

BRS-1255
https://bcparksdigital.atlassian.net/browse/BRS-1255
section updates

BRS-1255: migration to update sections

---

lambda/export-variance/invokable/index.js

API-222: Fixing missing variance note in exporter

---

.github/workflows/deploy_dev.yaml
.github/workflows/deploy_prod.yaml
.github/workflows/deploy_test.yaml
.github/workflows/on-pr.yaml

NOBUG: Updating workflows

---

lambda/constants.js
lambda/export-variance/invokable/index.js

BRS-232
[Ticket 232](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=39314088)
Add a column to the variance export to show status of resolved. 
*Sanitized note section of variance export to remove new lines to prevent formatting issues of CSV.

BRS-232: Add column variance export

---

lambda/export-variance/invokable/index.js

BRS-221
[Ticket-221](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=36561810)
Limit the decimal points in Variance % to 2.
Account for possibility of commas in Park Name, and Notes on the variance report.

BRS-221: Issues with Variance Report

---

terraform/src/nameUpdate.tf

Update the nodejs runtime to what's available in AWS.

NOBUG: Update nodejs.

---

terraform/src/db.tf

NOBUG: Update TF file.

---

terraform/src/roles.tf

Updates the role to allow index/cache table.

NOBUG: Update db role.

---

terraform/src/roles.tf

NOBUG: UpdateItem adjustment.

---

terraform/src/nameUpdate.tf

122: Update cronjob entry.

---

serverless.yml

NOBUG
Fixing serverless.com build issue, see https://github.com/bcgov/parks-reso-api/pull/331

NOBUG: Fix serverless.com build issue

---

lambda/nameUpdate/index.js

PDR-224
Updating nightly name data register cronjob to use the appropriate status `established` instead of `current`.

PDR-224 updating current state to established

---

.github/workflows/deploy_prod.yaml
.github/workflows/deploy_test.yaml
lambda/cloudwatchAlarm/index.js
terraform/src/cloudwatchAlarms.tf
terraform/src/variables.tf

Adds ms teams integration with deployment/cloudwatch alarms. Removes rocketchat.

231: MS Teams integration.

---

migrations-data/sectionUpdate2.js

BRS-276
[Ticket 276](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=43958427)
File uses the supplied ORC numbers and section names for each park to update section names. 
Gets a list of each subArea for the corresponding ORC and updates the section names with the new name supplied.

BRS-276: Migration for second round of section updates

---

docs/cloudformation_template.json
docs/data_model.json

Adding noSQL files for A&R data model

NOBUG adding datamodel and cf template for NoSQL

---

__tests__/subAreaUtils.test.js
lambda/subArea/POST/index.js
lambda/subAreaUtils.js

AR-293
https://github.com/bcgov/bcparks-ar-admin/issues/293
Updating subAreaPost to have correct roles.

AR-293-2: Updating subAreaPost to have correct roles

---

migrations-data/checkAllRecordsForORC.js
migrations-data/updateORC3883.js

BRS-289
[BRS-289](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=47053526)
Migration to convert park 3883 to 0281:
- Creates new park 
- Creates new sub areas
- Updates Activity Records
- Updates Configs of Activity Records
- Creates new Variance reports with updated ORC
- Deletes old variance reports
- Deletes old sub areas
- Deletes old park
checkAllRecordsForORC was a helper to search ORC for the following:
- If ORC exists
- If subareas exist
- Configs for any subAreas
- Activity records for subAreas
- Variances for any records

BRS-289:Change Park ORC#3883 and Name

---

__tests__/constants.test.js
lambda/constants.js
lambda/export/invokable/index.js

Relates to https://github.com/bcgov/bcparks-ar-admin/issues/256.

PDR-256 adding camping nights field

---

lambda/export/invokable/index.js

BRS-271
[271](https://github.com/bcgov/bcparks-ar-admin/issues/271)
Fix a typo for the Exporter status.

BRS-271: Fix typo in Exporter Report status

---

.github/workflows/deploy_dev.yaml
.github/workflows/deploy_prod.yaml
.github/workflows/deploy_test.yaml

BRS-291-3: Fix to Github Actions deploy

---

.github/workflows/deploy_dev.yaml
.github/workflows/deploy_prod.yaml
.github/workflows/deploy_test.yaml

Fix Github Actions for deployment (again)

BRS-291-4: Fix Github Actions for deployment (again)

---

README.md

BRS-291-8: NOBUG: build bump test

---

.github/workflows/on-pr.yaml
arSam/yarn.lock

Remove cache check and flag on SAM build

BRS-291-9: Remove cache check and flag on SAM build

---

.github/workflows/deploy_dev.yaml
.github/workflows/on-pr.yaml

- Fix cache check and flag on SAM build in dev_deploy
- Add back cache check and flag in on_pr

BRS-291-10: Fix cache check and flag on SAM build in dev_deploy

---

arSam/layers/subAreaLayer/Makefile

Try cache clean in subarealayer makefile

BRS-291-11: Try cache clean in subarealayer makefile

---

.github/workflows/deploy_dev.yaml

BRS-291-12: Delete stack name

---

arSam/template.yaml

Fix to config file, change stage to always be api

BRS-291-14: Fix to config file, change stage to always be api

---

arSam/handlers/activity/GET/index.js
arSam/handlers/activity/POST/index.js
arSam/handlers/export-variance/GET/index.js
arSam/handlers/export/GET/index.js
arSam/handlers/fiscalYearEnd/POST/index.js
arSam/handlers/park/GET/index.js
arSam/handlers/park/POST/index.js
arSam/handlers/subArea/POST/index.js
arSam/handlers/variance/GET/index.js
arSam/handlers/variance/PUT/index.js

[BRS-326](https://github.com/orgs/bcgov/projects/49/views/1?filterQuery=326&pane=issue&itemId=59089136)
[BRS-291](https://github.com/orgs/bcgov/projects/49/views/1?filterQuery=291&pane=issue&itemId=47054932)
- [Fixes from QA comment in 291](https://github.com/bcgov/bcparks-ar-api/issues/291#issuecomment-2257519096).

BRS-326-3: QA fixes for parkGet

---

arSam/handlers/activity/POST/package.json
arSam/handlers/cloudwatchAlarm/package.json
arSam/handlers/export/invokable/package.json
arSam/handlers/fiscalYearEnd/POST/package.json
arSam/handlers/nameUpdate/package.json
arSam/layers/baseLayer/nodejs/package.json
arSam/layers/constantsLayer/nodejs/package.json
arSam/layers/formulaLayer/nodejs/package.json
arSam/layers/functionsLayer/nodejs/package.json
arSam/layers/keycloakLayer/nodejs/package.json
arSam/layers/permissionLayer/nodejs/package.json
arSam/layers/subAreaLayer/nodejs/package.json
arSam/template.yaml

[BRS-326](https://github.com/orgs/bcgov/projects/49/views/1?filterQuery=326&pane=issue&itemId=59089136)
[BRS-291](https://github.com/orgs/bcgov/projects/49/views/1?filterQuery=291&pane=issue&itemId=47054932)
- [Fixes from QA comment in 291](https://github.com/bcgov/bcparks-ar-api/issues/291#issuecomment-2257519096).
- Increase timout on nameUpdate function call to 300s.
- change `author` to Team Osprey

BRS-326-4: QA fixes for nameUpdate

---

arSam/handlers/export-variance/invokable/index.js

[#357](https://github.com/bcgov/bcparks-ar-admin/issues/357)
- Fix variable name

BRS-357-1: Fix misnamed variable

---

arSam/migrations/20240913082200-updateToMarineSitesArea.js

BRS-368
[BRS-368](https://github.com/bcgov/bcparks-ar-admin/issues/368)
- Update Mount Titus, Phillips Creek, Wolf River, Rainbow Island, and Upper Campbell to new subarea "Marine Sites"
- Consolidate these records into one record
- Archive and lock the old records to be "historical" on frontend

BRS-368: Add Migration to Update to Marine Sites Subareas

---

arSam/handlers/export-missing/invokable/index.js

BRS-377
#377 
- Revamp the missing invokable to properly find and populate the CSV when the data provides 0 or `null` values.
- Fix bug in #374 where items that had commas in their names were creating new cells, such as ȽÁU,WELṈEW̱

BRS-377: Fix Missing Export for Null Values

---

.prettierrc.json
arSam/migrations/202410181342-fixDataDiscrepancies.js

BRS-380
#380
- Parse through the old and new database and consolidate any subarea changes, activity changes, and update any variances as needed. This will add missing activities and update any changed activity in the new database
- While running, the migration will create a `.txt` file of all the logs, documenting the changes

BRS-380: Consolidate Old and New Databases Discrepancies

---

arSam/disaster-recovery/README.md
arSam/disaster-recovery/config.js
arSam/disaster-recovery/functions.js
arSam/disaster-recovery/operations.js
arSam/disaster-recovery/operations/op-aws-backup-restore.js
arSam/disaster-recovery/operations/op-delete-table.js
arSam/disaster-recovery/operations/op-duplicate-table.js
arSam/disaster-recovery/operations/op-dynamo-backup.js
arSam/disaster-recovery/operations/op-dynamo-restore.js
arSam/disaster-recovery/operations/op-turn-on-deletion-protection.js
arSam/disaster-recovery/operations/op-turn-on-pitr.js
arSam/disaster-recovery/restore-dynamo.js
arSam/disaster-recovery/restore-options/perform-aws-backup-steps.js
arSam/disaster-recovery/restore-options/perform-backup-dynamo-duplicate.js
arSam/disaster-recovery/restore-options/perform-backup-dynamo-original.js
arSam/disaster-recovery/restore-options/perform-delete-table.js
arSam/disaster-recovery/restore-options/perform-duplicate-table.js
arSam/disaster-recovery/restore-options/perform-manual-restore-aws.js
arSam/disaster-recovery/restore-options/perform-manual-restore-dynamo.js
arSam/disaster-recovery/restore-options/perform-pitr-steps.js
arSam/disaster-recovery/restore-options/perform-restore-aws.js
arSam/disaster-recovery/restore-options/perform-restore-dynamo.js
arSam/disaster-recovery/restore-options/perform-turn-on-deletion-protection.js
arSam/disaster-recovery/restore-options/perform-turn-on-pitr.js

BRS-517
[#517](https://github.com/bcgov/parks-data-register/issues/517)
- Add Disaster Recovery script to AR
- The Disaster Recovery script will initiate the steps to restore, backup, and/or delete a table in DynamoDB
- Refer to the [README](https://github.com/bcgov/bcparks-ar-api/blob/6920a114ed135418febf9f43d5aea2a7d51197ec/arSam/disaster-recovery/README.md) for more information regarding the script processes.

[BRS-517] - Add Disaster Recovery Script

---

arSam/handlers/export-variance/invokable/index.js
arSam/layers/constantsLayer/constantsLayer.js

BRS-389
[#389](https://github.com/bcgov/bcparks-ar-admin/issues/389)
- Fix export headings, bring in Winter data into Variance and Missing exports

BRS-389-1 - Implement Winter Camping Data Fields (Fix)
